### ISSUE TITLE
Apply new knative runners to: map-reduce

### ISSUE THREAD

**Issue by dhschall** [vhive-serverless/vSwarm#265]

**Comment by alannair** [comment]
Issue has been fixed in the `aws_lambda_support` branch.
We may close this issue as soon as the PR [#298](https://github.com/vhive-serverless/vSwarm/pull/298) gets merged to `main`.

**Comment by ustiugov** [comment]
@alannair please just add to PR #298 description a note: "Closes #298" so this Issue would be closed automatically
