### ISSUE TITLE
Error when using INLINE transfer type in video-analytics

### ISSUE THREAD

**Issue by varungohil** [vhive-serverless/vSwarm#403]
**Describe the bug**
Documentation mentions that video analytics supports inline transfer. But on deploying it on a stock-only knative cluster on cloud lab, I get the following timeout error for decoder.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/25960514/209372660-c065c5cb-c5cb-4140-9c04-b818fa462c11.png">

The logs for the decoder container mention that INLINE transfer type is not supported. See the figure below:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/25960514/209372765-0d940730-321d-4879-87e6-f4a469e70946.png">

This is strange, since from the source file [decode.py](https://github.com/vhive-serverless/vSwarm/blob/main/benchmarks/video-analytics/decoder/decode.py) it looks like the inline transfer type is supported.

**To Reproduce**
Steps to reproduce the behavior.

- Setup vHive on CloudLab with stock-only option with the steps mentioned [here](https://github.com/vhive-serverless/vHive/blob/main/docs/quickstart_guide.md) 
- Deploy video analytics using the commands below:
```
cd vSwarm/benchmakrs/video-analytics
../../tools/kn_deploy.sh ./knative_yamls/inline/*
```

**Expected behavior**
Video-analytics is deployed succesfully. 

**Logs**
Log of decoder service:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/25960514/209372765-0d940730-321d-4879-87e6-f4a469e70946.png">

**Notes**
Currently, we support only Ubuntu 18 (x86) bare-metal hosts, however
we encourage the users to reports Issues that appear in different settings.
We will try to help and potentially include these scenarios into our CI
if given enough interest from the community.

**Comment by shyamjesal** [comment]
This is not supposed to happen. I will take a look and let you know soon.

**Comment by shyamjesal** [comment]
Hi @varungohil ,
Raised #404 to fix this.
