### ISSUE TITLE
Relay is not generating random inputs 

### ISSUE THREAD

**Issue by Nathees** [vhive-serverless/vSwarm#622]
@dhschall  Relay is not generating random inputs when the "--generator=random" flag is set. It always sends constant input (the input is "A random message") to the AES workload.

**Comment by dhschall** [comment]
This should be fixed in #630 
The reason is I forgot to update the version of vSwarm-proto. Its supported only after v0.4.1.
@Nathees  what you can do is you can, before this gets merged and too verify:
```
cd ./tools/relay
# Update dependencies with
go get -u
go mod tidy
# Build the relay container again
make relay-docker
```

Then try it again
