### ISSUE TITLE
Upgrade go version

### ISSUE THREAD

**Issue by dhschall** [vhive-serverless/vSwarm#691]
go is already stable with 1.21. Also upgrading tracing dependencies require at least go 1.19.
We need to upgrade the base images, mod files and CI workflows.

**Comment by dhschall** [comment]
@ustiugov vHive is already at 1.19. Are there plans to upgrade it soon?
I think it makes sense to keep them somehow in sync, given that you now depend on the tracing and invoker utils in vSwarm.
I can upgrade vSwarm to 1.19 before I create release v1.0.

**Comment by ustiugov** [comment]
@dhschall I don't think we should keep vHive and vSwarm in sync. Please go ahead and upgrade to 1.21
